---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    statsd:
    {{- range .Values.config.statsd }}
    - ip: {{ .ip | quote }}
      port: {{ .port | quote }}
      interval: {{ .interval }}
    {{- end }}
    databases:
    {{- range .Values.config.databases }}
    - type: {{ .type }}
      q: {{ .q | quote }}
      timeout: {{ .timeout }}
      endpoints:
      {{- range .endpoints }}
      - hostname: {{ .hostname }}
        user: {{ .user }}
        password: {{ .password | squote }}
        port: {{ .port }}
        ip: {{ .ip }}
        timeout: {{ .timeout }}
        q: {{ .q | quote }}
      {{- end }}
    {{- end }}
