---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}{{- with .Values.pinger.labels }}{{ toYaml . | nindent 4 }}{{- end }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }} # forces pods to redeploy on config change

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- with .Values.pinger.affinity }}
      affinity: {{ toYaml . | nindent 8 }}{{- end }}
      volumes:
      - name: {{ .Release.Name }}-config
        configMap:
          name: {{ .Release.Name }}-config
      {{- if .Values.pinger.tolerations}}
      tolerations: {{ toYaml .Values.pinger.tolerations | nindent 8 }}{{- end }}
      containers:
      - image: {{ .Values.pinger.imageRepo }}:{{ .Values.pinger.imagetag }}
        name: {{ .Release.Name }}
        volumeMounts:
        - name: {{ .Release.Name }}-config
          mountPath: /app/config.yaml
          subPath: config.yaml

        resources: {{ toYaml .Values.pinger.resources | nindent 10 }}
      restartPolicy: Always

