name: db-pinger
version: 1 # not a complete semver version because the build process fills in the minor and patch components
description: DB connectivity checking tool
keywords:
  - db-pinger
    dre
home: https://github.com/
sources:
  - https://github.com/
maintainers:
  - name: Dien Phan
    email: tdien105@gmail.com

engine: gotpl # The name of the template engine (optional, defaults to gotpl)
icon: ''
deprecated: false
